apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: promtest
  namespace: foo
spec:
  selector:
    matchLabels:
      run: promtest
  podMetricsEndpoints:
  - port: foo
    path: /