apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
  labels:
    app: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lab-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lab-app
    spec:
      containers:
      - name: lab
        image: lab:1
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "50m"
