apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: k8slab
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/henrikb77/k8slab
  ref:
    branch: main
  secretRef:
    name: auth2