apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
  labels:
    app: lab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: lab-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lab-app
    spec:
      containers:
      - name: lab
        image: lab:3
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "50m"
        readinessProbe:
          timeoutSeconds: 5
          failureThreshold: 2
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
        livenessProbe:
          timeoutSeconds: 5
          failureThreshold: 2
          httpGet:
            path: /live
            port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: lab-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
