apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
  labels:
    app: lab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: lab-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lab-app
    spec:
      containers:
      - name: lab
        image: lab:6
---
apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: lab-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000